### ISSUE TITLE
Calling GetAllAirports() returns an exception - An item with the same key has already been added.

### ISSUE THREAD

**Issue by thevlf** [ibistic/open-airport-data#6]
var airportProvider = new OpenFlightsDataAirportProvider(airportCache, new OpenFlightsDataCountryProvider(countriesCache));
                    Airports = airportProvider.GetAllAirports().ToList();                    

This results in an exception of : An item with the same key has already been added.

**Comment by magnusakselvoll** [comment]
Thank you @thevlf. This is an error in the source data. We have written a fix to address this. Version 1.1.0 will be available shortly.
